// ─── DiceBear v9 "avataaars" – valores exatos da API (camelCase) ─────────────

export type AvatarCategory =
    | 'top'
    | 'hairColor'
    | 'eyes'
    | 'eyebrows'
    | 'mouth'
    | 'skinColor'
    | 'clothing'
    | 'clothesColor'
    | 'accessories'
    | 'facialHair'
    | 'facialHairColor'
    | 'clothingGraphic'
    | 'hatColor';

export const AVATAR_OPTIONS: Record<string, readonly string[]> = {
    top: [
        'noHair',
        'eyepatch',
        'hat',
        'hijab',
        'turban',
        'winterHat1',
        'winterHat02',
        'winterHat03',
        'winterHat04',
        'bigHair',
        'bob',
        'bun',
        'curly',
        'curvy',
        'dreads',
        'frida',
        'fro',
        'froBand',
        'longButNotTooLong',
        'miaWallace',
        'shavedSides',
        'straight01',
        'straight02',
        'straightAndStrand',
        'dreads01',
        'dreads02',
        'frizzle',
        'shaggyMullet',
        'shortCurly',
        'shortFlat',
        'shortRound',
        'shortWaved',
        'sides',
        'theCaesar',
        'theCaesarAndSidePart',
    ],
    accessories: [
        'eyepatch',
        'kurt',
        'prescription01',
        'prescription02',
        'round',
        'sunglasses',
        'wayfarers',
    ],
    facialHair: [
        'beardMedium',
        'beardLight',
        'beardMajestic',
        'moustacheFancy',
        'moustacheMagnum',
    ],
    facialHairColor: [
        '2c1b18', '4a312c', '724133', 'a55728',
        'b58143', 'c93305', 'd6b370', 'e8e1e1', 'ecdcbf', 'f59797',
    ],
    clothing: [
        'blazerAndShirt',
        'blazerAndSweater',
        'collarAndSweater',
        'graphicShirt',
        'hoodie',
        'overall',
        'shirtCrewNeck',
        'shirtScoopNeck',
        'shirtVNeck',
    ],
    clothesColor: [
        '262e33', '3c4f5c', '65c9ff', '5199e4', '25557c',
        'e6e6e6', '929598', 'a7ffc4', 'b1e2ff', 'ffdeb5',
        'ff5c5c', 'ffffff', 'ff488e', 'ffafb9',
    ],
    clothingGraphic: [
        'bat', 'cumbia', 'deer', 'diamond', 'hola',
        'pizza', 'resist', 'skull', 'skullOutline', 'bear',
    ],
    eyes: [
        'closed',
        'cry',
        'default',
        'eyeRoll',
        'happy',
        'hearts',
        'side',
        'squint',
        'surprised',
        'wink',
        'winkWacky',
        'xDizzy',
    ],
    eyebrows: [
        'angry',
        'angryNatural',
        'default',
        'defaultNatural',
        'flatNatural',
        'raisedExcited',
        'raisedExcitedNatural',
        'sadConcerned',
        'sadConcernedNatural',
        'unibrowNatural',
        'upDown',
        'upDownNatural',
    ],
    mouth: [
        'concerned',
        'default',
        'disbelief',
        'eating',
        'grimace',
        'sad',
        'screamOpen',
        'serious',
        'smile',
        'tongue',
        'twinkle',
        'vomit',
    ],
    skinColor: [
        '614335', 'ae5d29', 'd08b5b', 'edb98a', 'f8d25c', 'fd9841', 'ffdbb4',
    ],
    hairColor: [
        '2c1b18', '4a312c', '724133', 'a55728',
        'b58143', 'c93305', 'd6b370', 'e8e1e1', 'ecdcbf', 'f59797',
    ],
    hatColor: [
        '262e33', '3c4f5c', '65c9ff', '5199e4', '25557c',
        'e6e6e6', '929598', 'a7ffc4', 'ffdeb5', 'ff5c5c', 'ffffff',
    ],
};

// Categorias que usam swatch de cor (círculo colorido)
export const COLOR_CATEGORIES = new Set([
    'hairColor', 'skinColor', 'facialHairColor', 'clothesColor', 'hatColor',
]);

// Labels legíveis por categoria
export const CATEGORY_LABELS: Record<string, string> = {
    top: 'Cabelo / Chapéu',
    accessories: 'Acessórios',
    facialHair: 'Barba / Bigode',
    facialHairColor: 'Cor da Barba',
    clothing: 'Roupas',
    clothesColor: 'Cor das Roupas',
    clothingGraphic: 'Estampa',
    eyes: 'Olhos',
    eyebrows: 'Sobrancelhas',
    mouth: 'Boca',
    skinColor: 'Tom de Pele',
    hairColor: 'Cor do Cabelo',
    hatColor: 'Cor do Chapéu',
};

export const READABLE_LABELS: Record<string, Record<string, string>> = {
    top: {
        noHair: 'Careca',
        eyepatch: 'Tapa-olho',
        hat: 'Chapéu',
        hijab: 'Hijab',
        turban: 'Turbante',
        winterHat1: 'Gorro 1',
        winterHat02: 'Gorro 2',
        winterHat03: 'Gorro 3',
        winterHat04: 'Gorro 4',
        bigHair: 'Longo Volumoso',
        bob: 'Bob',
        bun: 'Coque',
        curly: 'Cacheado',
        curvy: 'Ondulado',
        dreads: 'Dreads',
        frida: 'Frida',
        fro: 'Afro',
        froBand: 'Afro c/ Fita',
        longButNotTooLong: 'Médio',
        miaWallace: 'Mia Wallace',
        shavedSides: 'Raspado nas Laterais',
        straight01: 'Liso 1',
        straight02: 'Liso 2',
        straightAndStrand: 'Liso com Mecha',
        dreads01: 'Dreads Curto 1',
        dreads02: 'Dreads Curto 2',
        frizzle: 'Frisado',
        shaggyMullet: 'Mullet',
        shortCurly: 'Curto Cacheado',
        shortFlat: 'Curto Liso',
        shortRound: 'Curto Redondo',
        shortWaved: 'Curto Ondulado',
        sides: 'Raspado',
        theCaesar: 'Caesar',
        theCaesarAndSidePart: 'Caesar c/ Risca',
    },
    accessories: {
        eyepatch: 'Tapa-olho',
        kurt: 'Kurt',
        prescription01: 'Óculos 1',
        prescription02: 'Óculos 2',
        round: 'Redondo',
        sunglasses: 'Solar',
        wayfarers: 'Wayfarer',
    },
    facialHair: {
        beardMedium: 'Barba Média',
        beardLight: 'Barba Leve',
        beardMajestic: 'Barba Majestosa',
        moustacheFancy: 'Bigode Elegante',
        moustacheMagnum: 'Bigode Magnum',
    },
    clothing: {
        blazerAndShirt: 'Blazer e Camisa',
        blazerAndSweater: 'Blazer e Suéter',
        collarAndSweater: 'Gola e Suéter',
        graphicShirt: 'Camiseta Estampada',
        hoodie: 'Moletom',
        overall: 'Macacão',
        shirtCrewNeck: 'Camiseta Gola Careca',
        shirtScoopNeck: 'Camiseta Decote',
        shirtVNeck: 'Camiseta Gola V',
    },
    clothingGraphic: {
        bat: 'Morcego',
        cumbia: 'Cumbia',
        deer: 'Cervo',
        diamond: 'Diamante',
        hola: 'Hola',
        pizza: 'Pizza',
        resist: 'Resist',
        skull: 'Caveira',
        skullOutline: 'Caveira Outline',
        bear: 'Urso',
    },
    eyes: {
        closed: 'Fechado',
        cry: 'Chorando',
        default: 'Normal',
        eyeRoll: 'Revirando',
        happy: 'Feliz',
        hearts: 'Coração',
        side: 'Lateral',
        squint: 'Semicerrado',
        surprised: 'Surpreso',
        wink: 'Piscada',
        winkWacky: 'Piscada Maluca',
        xDizzy: 'Tonto',
    },
    eyebrows: {
        angry: 'Bravo',
        angryNatural: 'Bravo Natural',
        default: 'Normal',
        defaultNatural: 'Normal Natural',
        flatNatural: 'Plano Natural',
        raisedExcited: 'Animado',
        raisedExcitedNatural: 'Animado Natural',
        sadConcerned: 'Preocupado',
        sadConcernedNatural: 'Preocupado Natural',
        unibrowNatural: 'Monocelha',
        upDown: 'Irregular',
        upDownNatural: 'Irregular Natural',
    },
    mouth: {
        concerned: 'Preocupado',
        default: 'Normal',
        disbelief: 'Incrédulo',
        eating: 'Comendo',
        grimace: 'Grimace',
        sad: 'Triste',
        screamOpen: 'Gritando',
        serious: 'Sério',
        smile: 'Sorrindo',
        tongue: 'Língua',
        twinkle: 'Twinkle',
        vomit: 'Vomitando',
    },
};

export const COLOR_LABELS: Record<string, { name: string; hex: string }> = {
    // Hair / Facial hair
    '2c1b18': { name: 'Preto', hex: '#2c1b18' },
    '4a312c': { name: 'Castanho Escuro', hex: '#4a312c' },
    '724133': { name: 'Castanho', hex: '#724133' },
    'a55728': { name: 'Marrom', hex: '#a55728' },
    'b58143': { name: 'Loiro Escuro', hex: '#b58143' },
    'c93305': { name: 'Ruivo', hex: '#c93305' },
    'd6b370': { name: 'Loiro', hex: '#d6b370' },
    'e8e1e1': { name: 'Grisalho', hex: '#e8e1e1' },
    'ecdcbf': { name: 'Platinado', hex: '#ecdcbf' },
    'f59797': { name: 'Rosa', hex: '#f59797' },
    // Skin
    '614335': { name: 'Negro', hex: '#614335' },
    'ae5d29': { name: 'Moreno Escuro', hex: '#ae5d29' },
    'd08b5b': { name: 'Moreno', hex: '#d08b5b' },
    'edb98a': { name: 'Moreno Claro', hex: '#edb98a' },
    'f8d25c': { name: 'Pardo', hex: '#f8d25c' },
    'fd9841': { name: 'Bronzeado', hex: '#fd9841' },
    'ffdbb4': { name: 'Branco', hex: '#ffdbb4' },
    // Clothes / Hat colors
    '262e33': { name: 'Carvão', hex: '#262e33' },
    '3c4f5c': { name: 'Ardósia', hex: '#3c4f5c' },
    '65c9ff': { name: 'Azul Claro', hex: '#65c9ff' },
    '5199e4': { name: 'Azul', hex: '#5199e4' },
    '25557c': { name: 'Azul Escuro', hex: '#25557c' },
    'e6e6e6': { name: 'Cinza Claro', hex: '#e6e6e6' },
    '929598': { name: 'Cinza', hex: '#929598' },
    'a7ffc4': { name: 'Verde Menta', hex: '#a7ffc4' },
    'b1e2ff': { name: 'Azul Bebê', hex: '#b1e2ff' },
    'ffdeb5': { name: 'Pêssego', hex: '#ffdeb5' },
    'ff5c5c': { name: 'Vermelho', hex: '#ff5c5c' },
    'ffffff': { name: 'Branco', hex: '#ffffff' },
    'ff488e': { name: 'Rosa', hex: '#ff488e' },
    'ffafb9': { name: 'Rosa Claro', hex: '#ffafb9' },
};